name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: tsc
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: yarn
      - run: yarn install --frozen-lockfile
      - name: Run Biome
        run: npx biome ci .
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test
